apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: sx-cnpg
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: sx-cnpg-cloudnative-pg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sx-cnpg-cloudnative-pg
subjects:
  - kind: ServiceAccount
    name: sx-cnpg-cloudnative-pg
    namespace: cnpg
